#include <arpa/inet.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

#define PORT 8080
#define BUFFER_SIZE 1024

int main() {
  int sockfd;
  char buffer[BUFFER_SIZE];
  char vote[BUFFER_SIZE];
  struct sockaddr_in servaddr;

  // 1. Create UDP datagram socket
  if ((sockfd = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
    perror("Socket creation failed");
    exit(EXIT_FAILURE);
  }

  memset(&servaddr, 0, sizeof(servaddr));

  // 2. Configure server address
  servaddr.sin_family = AF_INET;
  servaddr.sin_port = htons(PORT);

  // Set to localhost for testing
  if (inet_pton(AF_INET, "127.0.0.1", &servaddr.sin_addr) <= 0) {
    perror("Invalid address or address not supported");
    close(sockfd);
    exit(EXIT_FAILURE);
  }

  // 3. Prompt user for candidate number
  printf("Available Candidates: 1, 2, 3\n");
  printf("Client sends: ");
  if (fgets(vote, sizeof(vote), stdin) == NULL) {
    perror("Error reading input");
    close(sockfd);
    exit(EXIT_FAILURE);
  }

  // Remove the newline character generated by fgets
  vote[strcspn(vote, "\n")] = 0;

  // 4. Send the vote to the server
  if (sendto(sockfd, vote, strlen(vote), 0, (const struct sockaddr *)&servaddr,
             sizeof(servaddr)) < 0) {
    perror("Sendto failed");
    close(sockfd);
    exit(EXIT_FAILURE);
  }

  // 5. Receive the server's reply
  socklen_t len = sizeof(servaddr);
  int n = recvfrom(sockfd, buffer, BUFFER_SIZE - 1, 0,
                   (struct sockaddr *)&servaddr, &len);

  if (n > 0) {
    buffer[n] = '\0';
    // 6. Print confirmation message
    printf("Server replies: %s\n", buffer);
  } else {
    perror("Error receiving response from server");
  }

  // 7. Clean up
  close(sockfd);
  return 0;
}
